# Generated by Django 3.2.13 on 2022-09-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effugium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawleveldata',
            name='rawData',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
