# Generated by Django 3.2.13 on 2022-09-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effugium', '0003_auto_20220928_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawleveldata',
            name='userIP',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
