# Generated by Django 3.2.13 on 2022-09-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effugium', '0004_rawleveldata_userip'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawleveldata',
            name='edata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawleveldata',
            name='parameters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
