# Generated by Django 4.0.4 on 2022-10-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effugium', '0005_auto_20220930_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawleveldata',
            name='completeAttempt',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
