# Generated by Django 3.2.13 on 2022-10-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effugium', '0006_rawleveldata_completeattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawleveldata',
            name='urlParameters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
